ignore changes to db identifier
traveloka/terraform-aws-rds-postgres pull request #46
Opened 2023-04-26 04:51 UTC by Trosfy

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #0000

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-rds-postgres/blob/master/CHANGELOG.md):

```release-note
NOTES:

* Any Notes regarding your submitted PR, like breaking changes or else.

FEATURES:

* **New Source:** `aws_000_0000` ([#references_to_issue](./))

ENHANCEMENTS:

* feature: Add support for new version of AWS API

BUG FIXES:

* Prevent error from evil bugs
```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan

```

2023-04-26 05:20 UTC, handojo1 commented
considering it is indeed a different instance, would rather create new terraform resources to ensure there is no leftover resources when decommisioning the old RDS

2023-04-26 05:20 UTC, handojo1 requested changes
This is a terrible idea, what if

2023-04-26 06:08 UTC, Trosfy commented
Yes, creating new terraform resource would ensure no leftovers, but even then, looking at the module it will generate new random id for the RDS identifier, which will force replacement if we import to the new resource.

2023-04-26 09:43 UTC, vincenttjia approved these changes

2023-04-26 09:44 UTC, nin9swells approved these changes

2023-04-27 02:54 UTC, handojo1 approved these changes

2023-04-27 03:07 UTC, merged